sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t miguelt/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true miguelt/docker-react npm run test